### ISSUE TITLE
Access is Denied at System.Runtime.Loader.AssemblyLoadContext.InternalLoad()

### ISSUE THREAD

**Issue by medeirosraul** [grandnode/grandnode#1048]
Hello,

I have a Grandnode e-commerce, and it runs perfectly. But, at some point it starts to give-me the error:

System.UnauthorizedAccessException: Access is denied. (0x80070005 (E_ACCESSDENIED)) at System.Runtime.Loader.AssemblyLoadContext.InternalLoad(ReadOnlySpan`1 arrAssembly, ReadOnlySpan`1 arrSymbols) at System.Reflection.Assembly.Load(Byte[] rawAssembly, Byte[] rawSymbolStore).

The error is commonsly associated with plugins. But plugins runs perfectly during a time. Perhaps, after hours of application running, this error occurs, and just runs perfectly again when I restart de application.

Any idea of what is happening?

Application is running on Azure Web App.

**Comment by medeirosraul** [comment]
This is the stacktrace

System.UnauthorizedAccessException: Access is denied. (0x80070005 (E_ACCESSDENIED)) at System.Runtime.Loader.AssemblyLoadContext.InternalLoad(ReadOnlySpan`1 arrAssembly, ReadOnlySpan`1 arrSymbols) at System.Reflection.Assembly.Load(Byte[] rawAssembly, Byte[] rawSymbolStore) at Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RuntimeViewCompiler.CompileAndEmit(RazorCodeDocument codeDocument, String generatedCode) at Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RuntimeViewCompiler.CompileAndEmit(String relativePath) at Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RuntimeViewCompiler.OnCacheMiss(String normalizedPath) --- End of stack trace from previous location where exception was thrown --- at Microsoft.AspNetCore.Mvc.Razor.Compilation.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath) at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage) at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromPath(String executingFilePath, String pagePath, Boolean isMainPage) at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.GetView(String executingFilePath, String viewPath, Boolean isMainPage) at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.GetView(String executingFilePath, String viewPath, Boolean isMainPage) at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult) at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result) at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|21_0(ResourceInvoker invoker, IActionResult result) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters() --- End of stack trace from previous location where exception was thrown --- at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync() --- End of stack trace from previous location where exception was thrown --- at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker) at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger) at Grand.Framework.Middleware.WorkContextMiddleware.Invoke(HttpContext context, IWorkContext workContext) in D:\Owl\source\CorujinhaPresentes\Grand.Framework\Middleware\WorkContextMiddleware.cs:line 71 at Grand.Framework.Middleware.StoreContextMiddleware.Invoke(HttpContext context, IStoreContext storeContext) in D:\Owl\source\CorujinhaPresentes\Grand.Framework\Middleware\StoreContextMiddleware.cs:line 44 at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext) at Grand.Framework.Middleware.PoweredByMiddleware.InvokeAsync(HttpContext context, IPoweredByMiddlewareOptions options) in D:\Owl\source\CorujinhaPresentes\Grand.Framework\Middleware\PoweredByMiddleware.cs:line 27 at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context) at Grand.Framework.Middleware.InstallUrlMiddleware.InvokeAsync(HttpContext context, IWebHelper webHelper) in D:\Owl\source\CorujinhaPresentes\Grand.Framework\Middleware\InstallUrlMiddleware.cs:line 50 at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

**Comment by PatrykPorabik** [comment]
Hi @medeirosraul 

In the case of your local path, it's ok, because stack trace contains a path where you have your source code locally if you publish your app from them.

In the case of error, it looks like a typical error when your directories don't have the proper permission. Can you ensure that all folders in your application have correct permissions? Maybe plugins are read-only or something.

**Comment by medeirosraul** [comment]
Hi @PatrykPorabik 

Yes, all folders have proper permission, and site is published in Azure Web Sites, where aways have full trust.

The strange thing is that the application runs normally for a while. However, it starts giving this error and starts running normally when the application is restarted. The application can run for hours or days normally, and suddenly it starts giving the error.

Before, I ran the local application pointing to the production database. So something I tried to do is create another database for development, and so far it has not had any more errors. Can there be any relation to running the development application pointing to the production database, and then the production application starts giving this error?
