### ISSUE TITLE
Manufacturer 'Show on Homepage' Exception with Default Install

### ISSUE THREAD

**Issue by wwrighter** [grandnode/grandnode#417]
**Environment:** 
Fresh installation of GrandNode 4.30 
- Selected "Show on Homepage" for the Apple Manufactuer (Catalog > Manufacturers) that is a default entry when installing with pre-populated data. 

**Expected:** 
Manufactuer logo to be displayed on the home page, either in default theme or as demo'd with market theme (markettheme.grandnode.com) scrolling along the bottom.

**Actual:**
Homepage loads with exception being thrown: 

System.InvalidOperationException: The view 'Components/HomePageManufacturers/Default' was not found. The following locations were searched:
/Themes/Market/Views/Home/Components/HomePageManufacturers/Default.cshtml
/Themes/Market/Views/Shared/Components/HomePageManufacturers/Default.cshtml
/Views/Home/Components/HomePageManufacturers/Default.cshtml
/Views/Shared/Components/HomePageManufacturers/Default.cshtml
/Pages/Shared/Components/HomePageManufacturers/Default.cshtml
   at Grand.Framework.Infrastructure.Extensions.ApplicationBuilderExtensions.<>c.<UseGrandExceptionHandler>b__1_1(HttpContext context) in /home/ubuntu/Downloads/source/grandnode/Grand.Framework/Infrastructure/Extensions/ApplicationBuilderExtensions.cs:line 83
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by wwrighter** [comment]
**Local temporary solution (Linux btw)**

sudo mv ./Themes/Market/Views/Shared/Components/HomepageManufacturers HomePageManufacturers
sudo mv ./Views/Shared/Components/HomepageManufacturers HomePageManufacturers

**Comment by PatrykPorabik** [comment]
Yes, it was typo.
