### ISSUE TITLE
Error occurring after uploaded a theme and activated the theme 

### ISSUE THREAD

**Issue by vijaytune** [grandnode/grandnode#592]
**Describe the bug**
Error occurring after uploaded a theme and activated the theme

Error details:
```
Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException
  HResult=0x80131500
  Message=One or more compilation failures occurred:
E:\kic\temp\grandnode_latestdev\Grand.Web\Themes\RedBlue\Views\Shared\Components\Footer\Default.cshtml(19,74): error CS1061: 'FooterModel.FooterTopicModel' does not contain a definition for 'IncludeInFooterColumn1' and no accessible extension method 'IncludeInFooterColumn1' accepting a first argument of type 'FooterModel.FooterTopicModel' could be found (are you missing a using directive or an assembly reference?)
E:\kic\temp\grandnode_latestdev\Grand.Web\Themes\RedBlue\Views\Shared\Components\Footer\Default.cshtml(53,74): error CS1061: 'FooterModel.FooterTopicModel' does not contain a definition for 'IncludeInFooterColumn2' and no accessible extension method 'IncludeInFooterColumn2' accepting a first argument of type 'FooterModel.FooterTopicModel' could be found (are you missing a using directive or an assembly reference?)
E:\kic\temp\grandnode_latestdev\Grand.Web\Themes\RedBlue\Views\Shared\Components\Footer\Default.cshtml(84,74): error CS1061: 'FooterModel.FooterTopicModel' does not contain a definition for 'IncludeInFooterColumn3' and no accessible extension method 'IncludeInFooterColumn3' accepting a first argument of type 'FooterModel.FooterTopicModel' could be found (are you missing a using directive or an assembly reference?)
  Source=Grand.Framework
  StackTrace:
   at Grand.Framework.Infrastructure.Extensions.ApplicationBuilderExtensions.<>c__DisplayClass1_0.<UseGrandExceptionHandler>b__1(HttpContext context) in E:\kic\temp\grandnode_latestdev\Grand.Framework\Infrastructure\Extensions\ApplicationBuilderExtensions.cs:line 92
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()

```

**To Reproduce**
1. Go to '/Admin/Setting/GeneralCommon'
2. Click on 'Store Information'
3. Upload a theme
4. Select the theme
5. Click Save button
6. Browse the guest site
7. See error

**Desktop (please complete the following information):**
 - Chrome

**Comment by PatrykPorabik** [comment]
Hi,
RedBlue Theme is not supported in GrandNode 4.50. It's still in the beta phase. After official release, we will upgrade our products to support 4.50 version.

**Comment by vijaytune** [comment]
Thank you.
