### ISSUE TITLE
Value cannot be null. (Parameter 'image')

### ISSUE THREAD

**Issue by rezabashiri** [grandnode/grandnode#835]
Im facing this issue frequently and its clear that the image service can not find the image in given path (it might be removed physically) 

To reproduce the exception remove an image from server without using admin panel and it will be shown

 System.ArgumentNullException: Value cannot be null. (Parameter 'image')
   at Grand.Services.Media.PictureService.ApplyResize(SKBitmap image, SKEncodedImageFormat format, Int32 targetSize) in /app/Grand.Services/Media/PictureService.cs:line 768
   at Grand.Services.Media.PictureService.GetPictureUrl(Picture picture, Int32 targetSize, Boolean showDefaultPicture, String storeLocation, PictureType defaultPictureType) in /app/Grand.Services/Media/PictureService.cs:line 436
   at Grand.Services.Media.PictureService.GetPictureUrl(String pictureId, Int32 targetSize, Boolean showDefaultPicture, String storeLocation, PictureType defaultPictureType) in /app/Grand.Services/Media/PictureService.cs:line 354

**Comment by rezabashiri** [comment]
I have tried to figure it out and it seems problem start from the code :
`protected virtual byte[] LoadPictureFromFile(string pictureId, string mimeType)
        {
            string lastPart = GetFileExtensionFromMimeType(mimeType);
            string fileName = string.Format("{0}_0.{1}", pictureId, lastPart);
            var filePath = GetPictureLocalPath(fileName);
            if (!File.Exists(filePath))
                return new byte[0];
            return File.ReadAllBytes(filePath);
        }` on line `   if (!File.Exists(filePath))
                return new byte[0];`

when it cant find the file it returns  `new byte[0]` that cause byte array be array with 0 index and later at `pictureBinary = await ApplyResize(image, EncodedImageFormat(picture.MimeType), targetSize); ` image be empty array . 

and it might be better check the image array count or at ApplyResize put try catch statement to prevent unhandle exception and user will insert image again

**Comment by KrzysztofPajak** [comment]
Please check this commit: https://github.com/grandnode/grandnode/commit/7546d351cea36f00f8f29fada7c30938faf0b9df
