### ISSUE TITLE
Error on order PDF invoice

### ISSUE THREAD

**Issue by Illia-M** [grandnode/grandnode#882]
**Describe the bug**
Order PDF invoice crash

**To Reproduce**
1. Place and process order
2. Click on 'PDF invoice'
3. See error "
INTERNAL ERROR
We're sorry, an internal error occurred.

    Our supporting staff has been notified of this error and will address the issue shortly.

    We apologize for the inconvenience.

    Please try clicking your browsers 'back' button or try reloading the home page.

    If you continue to receive this message, please try again in a little while.

    Thank you for your patience. 
"

**Expected behavior**
Get PDF file

**Desktop (please complete the following information):**
 - Firefox

**Additional context**
Stack trace
System.IO.IOException: file:///var/aspnetcore/GrandNode/wwwroot/content/images/thumbs/5f023e0bdbf24347b526819e.webp is not a recognized imageformat. at iTextSharp.text.Image.GetInstance(Uri url)
 at iTextSharp.text.Image.GetInstance(String filename)
 at Grand.Services.Commands.Handlers.Orders.PreparePdfOrderCommandHandler.PrepareOrderHeader(Order order, Language language, PdfSettings pdfSettings) in D:\GrandnodeGit\grandnode\Grand.Services\Commands\Handlers\Orders\PreparePdfOrderCommandHandler.cs:line 247 at Grand.Services.Commands.Handlers.Orders.PreparePdfOrderCommandHandler.PreparePdfOrder(Document doc, PdfWriter pdfWriter, Rectangle pageSize, Order order, String languageId, String vendorId) in D:\GrandnodeGit\grandnode\Grand.Services\Commands\Handlers\Orders\PreparePdfOrderCommandHandler.cs:line 119 at Grand.Services.Commands.Handlers.Orders.PreparePdfOrderCommandHandler.Handle(PreparePdfOrderCommand request, CancellationToken cancellationToken) in D:\GrandnodeGit\grandnode\Grand.Services\Commands\Handlers\Orders\PreparePdfOrderCommandHandler.cs:line 103 at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
 at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
 at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
 at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
 at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
 at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
 at Grand.Services.Common.PdfService.PrintOrdersToPdf(Stream stream, IList`1 orders, String languageId, String vendorId) in D:\GrandnodeGit\grandnode\Grand.Services\Common\PdfService.cs:line 147 at Grand.Web.Controllers.OrderController.GetPdfInvoice(String orderId, IPdfService pdfService) in D:\GrandnodeGit\grandnode\Grand.Web\Controllers\OrderController.cs:line 192 at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
 at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
 at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
 at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
 at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
 at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
 at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
 at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
 at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
 at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
 at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
 at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
 at Grand.Framework.Middleware.WorkContextMiddleware.Invoke(HttpContext context, IWorkContext workContext) in D:\GrandnodeGit\grandnode\Grand.Framework\Middleware\WorkContextMiddleware.cs:line 73 at Grand.Framework.Middleware.StoreContextMiddleware.Invoke(HttpContext context, IStoreContext storeContext) in D:\GrandnodeGit\grandnode\Grand.Framework\Middleware\StoreContextMiddleware.cs:line 44 at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
 at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
 at Grand.Framework.Middleware.PoweredByMiddleware.InvokeAsync(HttpContext context, IPoweredByMiddlewareOptions options) in D:\GrandnodeGit\grandnode\Grand.Framework\Middleware\PoweredByMiddleware.cs:line 27 at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
 at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
 at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
 at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
 at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
 at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
 at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

**Comment by TTomu** [comment]
I just test it on our demo, and can not reproduce issue. Can you try reproduce it again [here](https://demo.grandnode.com/)?

**Comment by Illia-M** [comment]
Try convert images to webp format, i think this is root of problem

**Comment by TTomu** [comment]
> Try convert images to webp format,
Issue is related to format of the image - that format is not supported by iTextSharp library.

**Comment by Illia-M** [comment]
I re-upload Logo image in PDF Settings and now all is fine :\

**Comment by Illia-M** [comment]
I think steps to reproduce Upload PDF logo -> Convert images to webp -> try create PDF invoice

**Comment by PatrykPorabik** [comment]
As long as ItextSharp won't support webp picture format, PDF printing feature won't work after converting. In that case, we are limited to its functionalities.
